# Generated by Django 5.2.15 on 2026-06-16 04:48
""" Initial migrations for the scheduler app. """

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchedulerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduler_id", models.CharField(max_length=160, unique=True)),
                ("hostname", models.CharField(max_length=160)),
                ("process_id", models.PositiveIntegerField()),
                ("last_tick_at", models.DateTimeField()),
                ("recent_claim_count", models.PositiveIntegerField(default=0)),
                ("recent_failure_count", models.PositiveIntegerField(default=0)),
                ("health_state", models.CharField(default="starting", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["scheduler_id"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                ("registered_task_name", models.CharField(max_length=160)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("one_time", "One time"),
                            ("interval", "Fixed interval"),
                            ("cron", "Cron"),
                        ],
                        max_length=24,
                    ),
                ),
                ("schedule_value", models.JSONField(default=dict)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "overlap_policy",
                    models.CharField(
                        choices=[
                            ("skip", "Skip"),
                            ("queue", "Queue"),
                            ("allow", "Allow"),
                        ],
                        default="skip",
                        max_length=16,
                    ),
                ),
                (
                    "misfire_policy",
                    models.CharField(
                        choices=[
                            ("coalesce", "Coalesce"),
                            ("catch_up", "Catch up"),
                            ("skip", "Skip"),
                        ],
                        default="coalesce",
                        max_length=16,
                    ),
                ),
                ("misfire_grace_seconds", models.PositiveIntegerField(default=60)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("retry_backoff_seconds", models.PositiveIntegerField(default=10)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("retention_count", models.PositiveIntegerField(default=500)),
                ("retention_days", models.PositiveIntegerField(default=30)),
                ("task_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["enabled", "next_run_at"],
                        name="job_enabled_next_run_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_attempts__gt", 0)),
                        name="job_max_attempts_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("timeout_seconds__gt", 0)),
                        name="job_timeout_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("retry_backoff_seconds__gte", 0)),
                        name="job_retry_backoff_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("run_after", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("retry_scheduled", "Retry scheduled"),
                            ("timed_out", "Timed out"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                            ("dead_lettered", "Dead lettered"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=220, unique=True),
                ),
                ("is_manual", models.BooleanField(default=False)),
                ("claimed_by", models.CharField(blank=True, max_length=160)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lease_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("output", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("worker_id", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="scheduler_app.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("due_detected", "Due detected"),
                            ("occurrence_created", "Occurrence created"),
                            ("occurrence_exists", "Occurrence already exists"),
                            ("claim", "Claim"),
                            ("dispatch", "Dispatch"),
                            ("worker_start", "Worker start"),
                            ("worker_finish", "Worker finish"),
                            ("failure", "Failure"),
                            ("retry_scheduled", "Retry scheduled"),
                            ("timeout", "Timeout"),
                            ("misfire", "Misfire"),
                            ("lease_recovery", "Lease recovery"),
                            ("dead_letter", "Dead letter"),
                            ("alert", "Alert"),
                            ("cache_invalidation", "Cache invalidation"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="scheduler_app.job",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="scheduler_app.jobexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeadLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=160)),
                ("final_error", models.TextField(blank=True)),
                ("attempts_used", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_letters",
                        to="scheduler_app.job",
                    ),
                ),
                (
                    "execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_letter",
                        to="scheduler_app.jobexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="scheduler_app.job",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="scheduler_app.jobexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_id", models.CharField(max_length=160, unique=True)),
                ("hostname", models.CharField(max_length=160)),
                ("process_id", models.PositiveIntegerField()),
                ("last_heartbeat_at", models.DateTimeField()),
                ("active_execution_count", models.PositiveIntegerField(default=0)),
                ("completed_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("health_state", models.CharField(default="starting", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worker_heartbeats",
                        to="scheduler_app.jobexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["worker_id"],
            },
        ),
        migrations.AddIndex(
            model_name="jobexecution",
            index=models.Index(
                fields=["status", "run_after"], name="execution_status_run_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobexecution",
            index=models.Index(
                fields=["job", "scheduled_for"], name="execution_job_sched_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobexecution",
            index=models.Index(fields=["lease_expires_at"], name="execution_lease_idx"),
        ),
        migrations.AddIndex(
            model_name="jobexecution",
            index=models.Index(
                fields=["job", "created_at"], name="execution_job_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_manual", False), ("scheduled_for__isnull", False)
                ),
                fields=("job", "scheduled_for"),
                name="unique_scheduled_occurrence",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_number__gt", 0)),
                name="execution_attempt_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="event_type_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(
                fields=["job", "created_at"], name="event_job_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(
                fields=["execution", "created_at"], name="event_exec_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["resolved", "created_at"], name="alert_resolved_created_idx"
            ),
        ),
    ]
