# Generated by Django 5.2.15 on 2026-06-18 20:26
""" Add alert mode and alter idempotency key. """

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="alert_mode",
            field=models.CharField(
                choices=[("log_only", "Log only"), ("web", "Web admin")],
                default="web",
                help_text="log_only emits structured log/event records; web also stores an operator-visible Alert row.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="idempotency_key",
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
