# Generated by Django 5.2.15 on 2026-06-18 21:01
""" Alter job alert mode. """

import scheduler_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_app", "0002_job_alert_mode_alter_jobexecution_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="alert_mode",
            field=models.CharField(
                choices=[("log_only", "Log only"), ("web", "Web admin")],
                default=scheduler_app.models.default_alert_mode,
                help_text="log_only emits structured log/event records; web also stores an operator-visible Alert row.",
                max_length=16,
            ),
        ),
    ]
